# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\FashionCycle.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QMainWindow, QApplication, QFileDialog, QAction,QMessageBox)
from PyQt5.QtGui import (QImage, QPainter, QPen)
from PyQt5.QtCore import (Qt, QPoint)
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 1000)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.canvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(0, 0, 1800, 1000))
        self.canvas.setObjectName("canvas")
        
        
        self.bookMarkSendFromCanvas = QtWidgets.QPushButton(self.centralwidget)
        self.bookMarkSendFromCanvas.setGeometry(QtCore.QRect(1310, 910, 101, 28))
        self.bookMarkSendFromCanvas.setStyleSheet("")
        self.bookMarkSendFromCanvas.setObjectName("bookMarkSendFromCanvas")
        
        self.PixelThicknessDialForPallete = QtWidgets.QDial(self.centralwidget)
        self.PixelThicknessDialForPallete.setGeometry(QtCore.QRect(950, 810, 151, 191))
        self.PixelThicknessDialForPallete.setObjectName("PixelThicknessDialForPallete")
        
        self.PixelThicknessValueForPallete = QtWidgets.QLCDNumber(self.centralwidget)
        self.PixelThicknessValueForPallete.setGeometry(QtCore.QRect(840, 880, 111, 61))
        self.PixelThicknessValueForPallete.setStyleSheet("border: 1px solid black;")
        self.PixelThicknessValueForPallete.setObjectName("PixelThicknessValueForPallete")
        
        self.chatBox = QtWidgets.QGroupBox(self.centralwidget)
        self.chatBox.setGeometry(QtCore.QRect(10, 10, 401, 951))
        self.chatBox.setStyleSheet("border: 1px solid black;")
        self.chatBox.setTitle("")
        self.chatBox.setFlat(True)
        self.chatBox.setObjectName("chatBox")
        
        self.chatMessageHistory = QtWidgets.QTextBrowser(self.chatBox)
        self.chatMessageHistory.setGeometry(QtCore.QRect(10, 30, 371, 871))
        self.chatMessageHistory.setMinimumSize(QtCore.QSize(311, 681))
        self.chatMessageHistory.setAutoFillBackground(False)
        self.chatMessageHistory.setObjectName("chatMessageHistory")
        
        self.bookMarkSend = QtWidgets.QPushButton(self.chatBox)
        self.bookMarkSend.setGeometry(QtCore.QRect(330, 910, 41, 28))
        self.bookMarkSend.setObjectName("bookMarkSend")
        
        self.chatMessage = QtWidgets.QTextEdit(self.chatBox)
        self.chatMessage.setGeometry(QtCore.QRect(10, 910, 261, 31))
        self.chatMessage.setObjectName("chatMessage")
        
        self.chatMessageSend = QtWidgets.QPushButton(self.chatBox)
        self.chatMessageSend.setGeometry(QtCore.QRect(280, 910, 41, 28))
        self.chatMessageSend.setObjectName("chatMessageSend")
        
        self.closeChatboxButton = QtWidgets.QPushButton(self.chatBox)
        self.closeChatboxButton.setGeometry(QtCore.QRect(0, 0, 93, 28))
        self.closeChatboxButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(255, 0, 0), stop:1 rgb(255, 0, 0));")
        self.closeChatboxButton.setObjectName("closeChatboxButton")
        
        self.bookMark = QtWidgets.QGroupBox(self.centralwidget)
        self.bookMark.setGeometry(QtCore.QRect(410, 10, 1021, 211))
        self.bookMark.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bookMark.setStyleSheet("border: 1px solid black;")
        self.bookMark.setTitle("")
        self.bookMark.setFlat(True)
        self.bookMark.setObjectName("bookMark")
        
        self.bookMarkLIstOfImages = QtWidgets.QComboBox(self.bookMark)
        self.bookMarkLIstOfImages.setGeometry(QtCore.QRect(260, 80, 531, 31))
        self.bookMarkLIstOfImages.setObjectName("bookMarkLIstOfImages")
        self.bookMarkLIstOfImages.addItem("")
        self.bookMarkLIstOfImages.addItem("")
        self.bookMarkLIstOfImages.addItem("")
        
        self.bookMarkSendFromControlNet_2 = QtWidgets.QPushButton(self.bookMark)
        self.bookMarkSendFromControlNet_2.setGeometry(QtCore.QRect(950, 180, 51, 28))
        self.bookMarkSendFromControlNet_2.setObjectName("bookMarkSendFromControlNet_2")
        
        self.closeBookMarkButton = QtWidgets.QPushButton(self.bookMark)
        self.closeBookMarkButton.setGeometry(QtCore.QRect(10, 0, 93, 28))
        self.closeBookMarkButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(255, 0, 0), stop:1 rgb(255, 0, 0));")
        self.closeBookMarkButton.setObjectName("closeBookMarkButton")
        
        self.controlNet = QtWidgets.QGroupBox(self.centralwidget)
        self.controlNet.setGeometry(QtCore.QRect(1430, 10, 371, 931))
        self.controlNet.setStyleSheet("border: 1px solid black;")
        self.controlNet.setTitle("")
        self.controlNet.setFlat(True)
        self.controlNet.setObjectName("controlNet")
        
        self.bookMarkSendFromControlNet = QtWidgets.QPushButton(self.controlNet)
        self.bookMarkSendFromControlNet.setGeometry(QtCore.QRect(140, 880, 101, 28))
        self.bookMarkSendFromControlNet.setObjectName("bookMarkSendFromControlNet")
        
        self.controlNetPromptInput = QtWidgets.QTextEdit(self.controlNet)
        self.controlNetPromptInput.setGeometry(QtCore.QRect(30, 120, 211, 31))
        self.controlNetPromptInput.setObjectName("controlNetPromptInput")
        
        self.controlNetSlider = QtWidgets.QSlider(self.controlNet)
        self.controlNetSlider.setGeometry(QtCore.QRect(120, 80, 160, 22))
        self.controlNetSlider.setOrientation(QtCore.Qt.Horizontal)
        self.controlNetSlider.setObjectName("controlNetSlider")
        
        self.controlNetValue = QtWidgets.QLCDNumber(self.controlNet)
        self.controlNetValue.setGeometry(QtCore.QRect(120, 30, 161, 41))
        self.controlNetValue.setObjectName("controlNetValue")
        
        self.controlNetImageList = QtWidgets.QListView(self.controlNet)
        self.controlNetImageList.setGeometry(QtCore.QRect(30, 210, 311, 621))
        self.controlNetImageList.setObjectName("controlNetImageList")
        
        self.controlNetSendPrompt = QtWidgets.QPushButton(self.controlNet)
        self.controlNetSendPrompt.setGeometry(QtCore.QRect(250, 120, 101, 28))
        self.controlNetSendPrompt.setStyleSheet("")
        self.controlNetSendPrompt.setObjectName("controlNetSendPrompt")
        
        self.bookMarkSelectionToSendControlNet = QtWidgets.QComboBox(self.controlNet)
        self.bookMarkSelectionToSendControlNet.setGeometry(QtCore.QRect(30, 160, 211, 31))
        self.bookMarkSelectionToSendControlNet.setObjectName("bookMarkSelectionToSendControlNet")
        self.bookMarkSelectionToSendControlNet.addItem("")
        self.bookMarkSelectionToSendControlNet.addItem("")
        self.bookMarkSelectionToSendControlNet.addItem("")
        
        self.controlNetSelectionToSendBookMark = QtWidgets.QComboBox(self.controlNet)
        self.controlNetSelectionToSendBookMark.setGeometry(QtCore.QRect(30, 850, 311, 22))
        self.controlNetSelectionToSendBookMark.setObjectName("controlNetSelectionToSendBookMark")
        self.controlNetSelectionToSendBookMark.addItem("")
        self.controlNetSelectionToSendBookMark.addItem("")
        self.controlNetSelectionToSendBookMark.addItem("")
        self.controlNetSelectionToSendBookMark.addItem("")
        
        self.closeControlNetButton = QtWidgets.QPushButton(self.controlNet)
        self.closeControlNetButton.setGeometry(QtCore.QRect(10, 0, 93, 28))
        self.closeControlNetButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(255, 0, 0), stop:1 rgb(255, 0, 0));")
        self.closeControlNetButton.setObjectName("closeControlNetButton")
        
        self.ChatbotTab = QtWidgets.QPushButton(self.centralwidget)
        self.ChatbotTab.setGeometry(QtCore.QRect(0, 460, 93, 28))
        self.ChatbotTab.setObjectName("ChatbotTab")
        self.ChatbotTab.setVisible(False)
        
        self.BookmarkTab = QtWidgets.QPushButton(self.centralwidget)
        self.BookmarkTab.setGeometry(QtCore.QRect(870, 20, 93, 28))
        self.BookmarkTab.setObjectName("BookmarkTab")
        self.BookmarkTab.setVisible(False)
        
        self.ControlNet = QtWidgets.QPushButton(self.centralwidget)
        self.ControlNet.setGeometry(QtCore.QRect(1710, 460, 93, 28))
        self.ControlNet.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.ControlNet.setObjectName("ControlNet")
        self.ControlNet.setVisible(False)
        
        self.canvas.raise_()
        
        self.BookmarkTab.raise_()
        
        self.ControlNet.raise_()
        
        self.ChatbotTab.raise_()
        
        self.bookMarkSendFromCanvas.raise_()
        
        self.PixelThicknessDialForPallete.raise_()
        
        self.PixelThicknessValueForPallete.raise_()
        
        self.bookMark.raise_()
        
        self.chatBox.raise_()
        
        self.controlNet.raise_()
        
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1791, 26))
        self.menubar.setObjectName("menubar")
        
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        
        MainWindow.setStatusBar(self.statusbar)
    #untouched generated code starts here
        self.retranslateUi(MainWindow)
        self.controlNetSlider.sliderMoved['int'].connect(self.controlNetValue.display) # type: ignore
        self.PixelThicknessDialForPallete.sliderMoved['int'].connect(self.PixelThicknessValueForPallete.display) # type: ignore
        self.closeControlNetButton.clicked.connect(self.controlNet.close) # type: ignore
        self.closeBookMarkButton.clicked.connect(self.bookMark.close) # type: ignore
        self.closeChatboxButton.clicked.connect(self.chatBox.close) # type: ignore
        self.ControlNet.clicked.connect(self.controlNet.show) # type: ignore
        self.BookmarkTab.clicked.connect(self.bookMark.show) # type: ignore
        self.ChatbotTab.clicked.connect(self.chatBox.show) # type: ignore
        self.closeControlNetButton.clicked.connect(self.ControlNet.show) # type: ignore
        self.ControlNet.clicked.connect(self.ControlNet.hide) # type: ignore
        self.closeBookMarkButton.clicked.connect(self.BookmarkTab.show) # type: ignore
        self.BookmarkTab.clicked.connect(self.BookmarkTab.hide) # type: ignore
        self.ChatbotTab.clicked.connect(self.ChatbotTab.hide) # type: ignore
        self.closeChatboxButton.clicked.connect(self.ChatbotTab.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    #untouched generated code ends here
        self.chatMessageSend.clicked.connect(self.send_message_to_Chatbot)
    #untouched generated code starts here
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bookMarkSendFromCanvas.setText(_translate("MainWindow", "Book Mark"))
        self.chatMessageHistory.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.bookMarkSend.setText(_translate("MainWindow", "BM"))
        self.chatMessageSend.setText(_translate("MainWindow", "Send"))
        self.closeChatboxButton.setText(_translate("MainWindow", "Close"))
        self.bookMarkLIstOfImages.setItemText(0, _translate("MainWindow", "Nice"))
        self.bookMarkLIstOfImages.setItemText(1, _translate("MainWindow", "NotNice"))
        self.bookMarkLIstOfImages.setItemText(2, _translate("MainWindow", "Comething"))
        self.bookMarkSendFromControlNet_2.setText(_translate("MainWindow", "Display"))
        self.closeBookMarkButton.setText(_translate("MainWindow", "Close"))
        self.bookMarkSendFromControlNet.setText(_translate("MainWindow", "Book Mark"))
        self.controlNetSendPrompt.setText(_translate("MainWindow", "Send"))
        self.bookMarkSelectionToSendControlNet.setItemText(0, _translate("MainWindow", "Nice"))
        self.bookMarkSelectionToSendControlNet.setItemText(1, _translate("MainWindow", "NotNice"))
        self.bookMarkSelectionToSendControlNet.setItemText(2, _translate("MainWindow", "Comething"))
        self.controlNetSelectionToSendBookMark.setItemText(0, _translate("MainWindow", "Choice 1"))
        self.controlNetSelectionToSendBookMark.setItemText(1, _translate("MainWindow", "Choice 2"))
        self.controlNetSelectionToSendBookMark.setItemText(2, _translate("MainWindow", "Choice 3"))
        self.controlNetSelectionToSendBookMark.setItemText(3, _translate("MainWindow", "Choice 4"))
        self.closeControlNetButton.setText(_translate("MainWindow", "Close"))
        self.ChatbotTab.setText(_translate("MainWindow", "Chatbot"))
        self.BookmarkTab.setText(_translate("MainWindow", "Book Mark"))
        self.ControlNet.setText(_translate("MainWindow", "ControlNet"))
    #untouched generated code ends here
    def send_message_to_Chatbot(self):
        print(chatMessage)
        message = chatMessage.toPlainText()
        self.chatMessage.clear()
        self.chatMessageHistory.append(f"User: {message}")
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
